# Generated by Django 2.2.2 on 2019-11-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('M_user', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('M_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='savemodel',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
