# Generated by Django 2.2.2 on 2019-11-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191109_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchantmodel',
            fields=[
                ('p_no', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('p_price', models.FloatField()),
                ('p_qty', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='savemodel',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
