# Generated by Django 2.2.2 on 2019-11-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191111_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantmodel',
            name='merchant',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app1.Savemodel'),
        ),
    ]
